// AUTO-GENERATED by scripts/generate-from-source.js — do not edit by hand.
import type { MetaRecord } from 'nextra'

export default {
  index: 'Overview',
  "analytics": "Analytics",
  "auth": "Auth",
  "brands": "Brands",
  "briefing": "Briefing",
  "creators": "Creators",
  "dashboard": "Dashboard",
  "email-agent": "Email-agent",
  "franchise": "Franchise",
  "loyalty": "Loyalty",
  "menu": "Menu",
  "orders": "Orders",
  "reservations": "Reservations",
  "restaurants": "Restaurants",
  "reviews": "Reviews",
  "stocks": "Stocks",
  "suppliers": "Suppliers",
  "tables": "Tables",
} satisfies MetaRecord
