#!/usr/bin/env node
/**
 * generate-docs.js — Grubano docs auto-generator (Agent 5)
 *
 * Reads the main app repo and regenerates two parts of this docs site:
 *   1. content/api/*.mdx        ← parsed from app/api/ ** /route.ts
 *   2. content/changelog/index.mdx ← parsed from `git log`
 *
 * The main app repo is located via (in order):
 *   - $APP_REPO_PATH
 *   - ../grubano-kitchen-hub   (CI checkout name)
 *   - ../grubano               (local dev checkout name)
 *
 * Pages under content/ (guides, getting-started, index) are hand-written
 * and never touched by this script.
 *
 * Usage: node scripts/generate-docs.js
 */

const fs = require('fs')
const path = require('path')
const { execSync } = require('child_process')

// ── Locate repos ────────────────────────────────────────────────────────────

const DOCS_ROOT = path.resolve(__dirname, '..')
const CONTENT_DIR = path.join(DOCS_ROOT, 'content')

function resolveAppRepo() {
  const candidates = [
    process.env.APP_REPO_PATH,
    path.resolve(DOCS_ROOT, '..', 'grubano-kitchen-hub'),
    path.resolve(DOCS_ROOT, '..', 'grubano'),
  ].filter(Boolean)

  for (const c of candidates) {
    if (fs.existsSync(path.join(c, 'app', 'api'))) return c
  }
  throw new Error(
    `Could not find the main app repo. Tried:\n  ${candidates.join('\n  ')}\n` +
      `Set APP_REPO_PATH to the grubano-kitchen-hub checkout.`,
  )
}

const APP_REPO = resolveAppRepo()
const API_DIR = path.join(APP_REPO, 'app', 'api')

console.log(`[generate-docs] app repo : ${APP_REPO}`)
console.log(`[generate-docs] docs root: ${DOCS_ROOT}`)

// ── Helpers ──────────────────────────────────────────────────────────────────

const AUTOGEN_BANNER =
  '{/* AUTO-GENERATED by scripts/generate-docs.js — do not edit by hand. */}'

function walk(dir, filter) {
  const out = []
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) out.push(...walk(full, filter))
    else if (filter(full)) out.push(full)
  }
  return out
}

/** Turn an absolute route.ts path into a public endpoint, e.g. /api/orders/{id}/status */
function routeToEndpoint(filePath) {
  const rel = path
    .relative(path.join(APP_REPO, 'app'), filePath)
    .replace(/\\/g, '/')
    .replace(/\/route\.ts$/, '')
  // [id] -> {id}, [...nextauth] -> {...nextauth}
  return (
    '/' +
    rel
      .split('/')
      .map((seg) => seg.replace(/^\[\.\.\.(.+)\]$/, '{...$1}').replace(/^\[(.+)\]$/, '{$1}'))
      .join('/')
  )
}

/** Top-level resource group, e.g. /api/loyalty/register -> "loyalty" */
function endpointGroup(endpoint) {
  const parts = endpoint.split('/').filter(Boolean) // ["api", "loyalty", ...]
  return parts[1] || 'misc'
}

const HTTP_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE']

function extractMethods(src) {
  return HTTP_METHODS.filter((m) =>
    new RegExp(`export\\s+(async\\s+)?function\\s+${m}\\b`).test(src),
  )
}

function extractAuth(src) {
  if (/CRON_SECRET/.test(src)) return 'CRON_SECRET'
  if (/getToken|getServerSession|authOptions/.test(src)) return 'session'
  return 'public'
}

/** Query params referenced via searchParams.get('x') */
function extractQueryParams(src) {
  const params = new Set()
  for (const m of src.matchAll(/searchParams\.get\(\s*['"`]([^'"`]+)['"`]\s*\)/g)) {
    params.add(m[1])
  }
  return [...params]
}

/** Best-effort parse of the FIRST z.object({ ... }) body schema in the file. */
function extractBodySchema(src) {
  const start = src.indexOf('z.object({')
  if (start === -1) return []
  // balance braces from the opening {
  let i = src.indexOf('{', start)
  let depth = 0
  let end = -1
  for (; i < src.length; i++) {
    if (src[i] === '{') depth++
    else if (src[i] === '}') {
      depth--
      if (depth === 0) {
        end = i
        break
      }
    }
  }
  if (end === -1) return []
  const body = src.slice(src.indexOf('{', start) + 1, end)

  const fields = []
  // match "name: z.<...>" at the top level (single line per field in these files)
  for (const line of body.split('\n')) {
    const m = line.match(/^\s*([a-zA-Z0-9_]+)\s*:\s*z\.(.+?),?\s*$/)
    if (!m) continue
    const name = m[1]
    const chain = m[2]
    const baseType = (chain.match(/^([a-zA-Z]+)/) || [])[1] || 'unknown'
    const required = !/\.optional\(\)|\.default\(/.test(chain)
    let detail = baseType
    const enumMatch = chain.match(/enum\(\[([^\]]+)\]\)/)
    if (enumMatch) {
      detail = 'enum: ' + enumMatch[1].replace(/['"`]/g, '').replace(/\s+/g, ' ').trim()
    }
    const defMatch = chain.match(/\.default\(([^)]+)\)/)
    if (defMatch) detail += ` (défaut: ${defMatch[1].replace(/['"`]/g, '')})`
    fields.push({ name, type: detail, required })
  }
  return fields
}

function extractStatusCodes(src) {
  const codes = new Set()
  for (const m of src.matchAll(/status:\s*(\d{3})/g)) codes.add(Number(m[1]))
  // Successful 200 responses often use NextResponse.json without an explicit status
  if (/NextResponse\.json\(/.test(src)) codes.add(200)
  return [...codes].sort((a, b) => a - b)
}

const STATUS_TEXT = {
  200: 'OK',
  201: 'Créé',
  400: 'Requête invalide',
  401: 'Authentification requise',
  403: 'Accès refusé',
  404: 'Introuvable',
  409: 'Conflit',
  422: 'Données non traitables',
  500: 'Erreur serveur',
}

// ── Parse all routes ──────────────────────────────────────────────────────────

const routeFiles = walk(API_DIR, (f) => f.endsWith('route.ts'))

const routes = routeFiles.map((file) => {
  const src = fs.readFileSync(file, 'utf8')
  const endpoint = routeToEndpoint(file)
  return {
    file,
    endpoint,
    group: endpointGroup(endpoint),
    methods: extractMethods(src),
    auth: extractAuth(src),
    query: extractQueryParams(src),
    body: extractBodySchema(src),
    statuses: extractStatusCodes(src),
  }
})

// group -> routes[]
const groups = {}
for (const r of routes) {
  ;(groups[r.group] ||= []).push(r)
}
for (const g of Object.keys(groups)) {
  groups[g].sort((a, b) => a.endpoint.localeCompare(b.endpoint))
}

// ── Render an API group page ──────────────────────────────────────────────────

const AUTH_BADGE = {
  public: '🌐 Public',
  session: '🔒 Session requise',
  CRON_SECRET: '🤖 CRON_SECRET',
}

function renderGroupPage(group, groupRoutes) {
  const title = group.charAt(0).toUpperCase() + group.slice(1)
  const lines = []
  lines.push('---')
  lines.push(`title: API — ${title}`)
  lines.push(`description: Référence des endpoints /api/${group}`)
  lines.push('---')
  lines.push('')
  lines.push(AUTOGEN_BANNER)
  lines.push('')
  lines.push(`# API — ${title}`)
  lines.push('')
  lines.push(`${groupRoutes.length} endpoint(s) under \`/api/${group}\`.`)
  lines.push('')

  for (const r of groupRoutes) {
    lines.push(`## \`${r.methods.join(' · ') || 'GET'}\` \`${r.endpoint}\``)
    lines.push('')
    lines.push(`**Auth:** ${AUTH_BADGE[r.auth]}`)
    lines.push('')

    if (r.query.length) {
      lines.push('**Query parameters**')
      lines.push('')
      lines.push('| Paramètre | Source |')
      lines.push('|---|---|')
      for (const q of r.query) lines.push(`| \`${q}\` | query string |`)
      lines.push('')
    }

    if (r.body.length) {
      lines.push('**Body (JSON)**')
      lines.push('')
      lines.push('| Champ | Type | Requis |')
      lines.push('|---|---|---|')
      for (const f of r.body) {
        lines.push(`| \`${f.name}\` | ${f.type} | ${f.required ? 'oui' : 'non'} |`)
      }
      lines.push('')
    }

    if (r.statuses.length) {
      lines.push('**Réponses**')
      lines.push('')
      lines.push('| Code | Signification |')
      lines.push('|---|---|')
      for (const s of r.statuses) lines.push(`| \`${s}\` | ${STATUS_TEXT[s] || ''} |`)
      lines.push('')
    }
  }

  return lines.join('\n') + '\n'
}

// ── Render API overview + meta ────────────────────────────────────────────────

function renderApiIndex() {
  const lines = []
  lines.push('---')
  lines.push('title: API Reference')
  lines.push('description: Vue d\'ensemble de l\'API REST Grubano')
  lines.push('---')
  lines.push('')
  lines.push(AUTOGEN_BANNER)
  lines.push('')
  lines.push('# API Reference')
  lines.push('')
  lines.push(`L'API REST Grubano expose **${routes.length} endpoints**. Tous les corps de requête sont validés avec [Zod](https://zod.dev) et les réponses sont au format JSON.`)
  lines.push('')
  lines.push('## Tous les endpoints')
  lines.push('')
  lines.push('| Méthodes | Endpoint | Auth |')
  lines.push('|---|---|---|')
  for (const r of [...routes].sort((a, b) => a.endpoint.localeCompare(b.endpoint))) {
    lines.push(`| \`${r.methods.join(' · ') || 'GET'}\` | \`${r.endpoint}\` | ${AUTH_BADGE[r.auth]} |`)
  }
  lines.push('')
  return lines.join('\n') + '\n'
}

function renderApiMeta(groupNames) {
  const lines = []
  lines.push('// AUTO-GENERATED by scripts/generate-docs.js — do not edit by hand.')
  lines.push("import type { MetaRecord } from 'nextra'")
  lines.push('')
  lines.push('export default {')
  lines.push("  index: 'Vue d\\'ensemble',")
  for (const g of groupNames) {
    const title = g.charAt(0).toUpperCase() + g.slice(1)
    lines.push(`  ${JSON.stringify(g)}: ${JSON.stringify(title)},`)
  }
  lines.push('} satisfies MetaRecord')
  return lines.join('\n') + '\n'
}

// ── Render changelog ───────────────────────────────────────────────────────────

const TYPE_LABEL = {
  feat: '✨ Nouveautés',
  fix: '🐛 Corrections',
  docs: '📝 Documentation',
  chore: '🔧 Maintenance',
  refactor: '♻️ Refactoring',
  perf: '⚡ Performance',
  test: '✅ Tests',
  style: '💅 Style',
}

function renderChangelog() {
  let raw = ''
  try {
    raw = execSync('git log -50 --date=short --pretty=format:%ad%x09%s', {
      cwd: APP_REPO,
      encoding: 'utf8',
    })
  } catch (err) {
    console.warn('[generate-docs] git log failed:', err.message)
    raw = ''
  }

  const byDate = new Map() // date -> [{type, scope, subject}]
  for (const line of raw.split('\n').filter(Boolean)) {
    const [date, subject = ''] = line.split('\t')
    const m = subject.match(/^(\w+)(?:\(([^)]+)\))?:\s*(.+)$/)
    const entry = m
      ? { type: m[1], scope: m[2] || null, subject: m[3] }
      : { type: 'other', scope: null, subject }
    if (!byDate.has(date)) byDate.set(date, [])
    byDate.get(date).push(entry)
  }

  const lines = []
  lines.push('---')
  lines.push('title: Changelog')
  lines.push('description: Historique des changements de la plateforme Grubano')
  lines.push('---')
  lines.push('')
  lines.push(AUTOGEN_BANNER)
  lines.push('')
  lines.push('# Changelog')
  lines.push('')
  lines.push('Généré automatiquement depuis les commits du dépôt principal.')
  lines.push('')

  const dates = [...byDate.keys()].sort().reverse()
  for (const date of dates) {
    lines.push(`## ${date}`)
    lines.push('')
    const entries = byDate.get(date)
    const byType = {}
    for (const e of entries) (byType[e.type] ||= []).push(e)
    const typeOrder = Object.keys(TYPE_LABEL).filter((t) => byType[t]).concat(
      byType.other ? ['other'] : [],
    )
    for (const type of typeOrder) {
      lines.push(`**${TYPE_LABEL[type] || '📦 Autres'}**`)
      lines.push('')
      for (const e of byType[type]) {
        const scope = e.scope ? `**${e.scope}** — ` : ''
        lines.push(`- ${scope}${e.subject}`)
      }
      lines.push('')
    }
  }

  if (!dates.length) lines.push('_Aucun commit trouvé._\n')

  return lines.join('\n') + '\n'
}

function renderChangelogMeta() {
  return (
    '// AUTO-GENERATED by scripts/generate-docs.js — do not edit by hand.\n' +
    "import type { MetaRecord } from 'nextra'\n\n" +
    'export default {\n' +
    "  index: 'Changelog',\n" +
    '} satisfies MetaRecord\n'
  )
}

// ── Write everything ───────────────────────────────────────────────────────────

function writeFile(relPath, contents) {
  const full = path.join(CONTENT_DIR, relPath)
  fs.mkdirSync(path.dirname(full), { recursive: true })
  fs.writeFileSync(full, contents, 'utf8')
  console.log(`[generate-docs] wrote ${relPath}`)
}

const groupNames = Object.keys(groups).sort()

writeFile('api/index.mdx', renderApiIndex())
writeFile('api/_meta.ts', renderApiMeta(groupNames))
for (const g of groupNames) {
  writeFile(`api/${g}.mdx`, renderGroupPage(g, groups[g]))
}

writeFile('changelog/index.mdx', renderChangelog())
writeFile('changelog/_meta.ts', renderChangelogMeta())

console.log(
  `[generate-docs] done — ${routes.length} endpoints across ${groupNames.length} groups.`,
)
