#!/usr/bin/env node
/**
 * translate-content.js — Grubano docs translator (Agent 5)
 *
 * Sections and translation directions:
 *   api/        EN → fr, es, ar, it   (generated by generate-from-source.js)
 *   changelog/  EN → fr, es, ar, it   (generated by generate-from-source.js)
 *   guides/     FR → en, es, ar, it   (source = FR, generated by
 *                                      generate-feature-page.js + editorial)
 *   root pages  FR → es, ar, it       (getting-started.mdx — en already exists;
 *                                      index.mdx is hand-authored per locale)
 *
 * Idempotent: each source file embeds a `sourceHash` in its frontmatter (or,
 * for editorial pages without one, we hash the source content). The hash is
 * carried into the translated file; on re-runs a target whose hash matches
 * the source is skipped — no API call.
 *
 * Guides are MDX with React components (Faq, JourneyStrip, FlowDiagram…):
 * user-visible string props and Mermaid node labels ARE translated; component
 * names, prop names, icon identifiers and link targets are preserved. After
 * translation, internal /fr/ links are re-pointed to the target locale and
 * elision apostrophes inside prop strings are normalised to ’ (MDX-safe).
 *
 * _meta.ts: api/changelog get their tiny auto _meta; guides/_meta.ts files
 * are HAND-AUTHORED per locale (sidebar labels) — never overwritten here.
 *
 * Required env:
 *   ANTHROPIC_API_KEY
 *
 * Optional env:
 *   ANTHROPIC_MODEL          (default: claude-sonnet-4-5)
 *   TRANSLATE_CONCURRENCY    (default: 4)
 *   TRANSLATE_LANGS          (default: en,fr,es,ar,it — intersected per section)
 *   TRANSLATE_SECTIONS       (default: api,changelog,guides,root)
 *   TRANSLATE_DRY_RUN=1      (skip API calls; print plan)
 *
 * Usage:
 *   ANTHROPIC_API_KEY=sk-ant-... node scripts/translate-content.js
 */

const fs = require('fs')
const path = require('path')
const crypto = require('crypto')

// ── Config ───────────────────────────────────────────────────────────────────

const DOCS_ROOT = path.resolve(__dirname, '..')
const CONTENT_DIR = path.join(DOCS_ROOT, 'content')

const LANG_FILTER = (process.env.TRANSLATE_LANGS || 'en,fr,es,ar,it')
  .split(',')
  .map((s) => s.trim())
  .filter(Boolean)
const SECTION_FILTER = (process.env.TRANSLATE_SECTIONS || 'api,changelog,guides,root')
  .split(',')
  .map((s) => s.trim())
  .filter(Boolean)

// name: content subdir ('' = locale root). kind drives the prompt flavour.
// files: explicit list (root) — otherwise every .mdx in the dir.
const SECTIONS = [
  { name: 'api', srcLang: 'en', targets: ['fr', 'es', 'ar', 'it'], kind: 'api' },
  { name: 'changelog', srcLang: 'en', targets: ['fr', 'es', 'ar', 'it'], kind: 'api' },
  { name: 'guides', srcLang: 'fr', targets: ['en', 'es', 'ar', 'it'], kind: 'guide' },
  { name: '', key: 'root', srcLang: 'fr', targets: ['es', 'ar', 'it'], kind: 'guide', files: ['getting-started.mdx'] },
]

const MODEL = process.env.ANTHROPIC_MODEL || 'claude-sonnet-4-5'
const CONCURRENCY = Math.max(1, Number(process.env.TRANSLATE_CONCURRENCY || 4))
const DRY_RUN = process.env.TRANSLATE_DRY_RUN === '1'
const API_KEY = process.env.ANTHROPIC_API_KEY

const LANG_NAME = {
  en: 'English',
  fr: 'French',
  es: 'Spanish',
  ar: 'Arabic',
  it: 'Italian',
}

// Localized label for the auto-generated section index entry (api/changelog).
const INDEX_LABEL = {
  api: { en: 'Overview', fr: "Vue d'ensemble", es: 'Resumen', ar: 'نظرة عامة', it: 'Panoramica' },
  changelog: {
    en: 'Changelog',
    fr: 'Journal des modifications',
    es: 'Registro de cambios',
    ar: 'سجل التغييرات',
    it: 'Registro delle modifiche',
  },
}

if (!DRY_RUN && !API_KEY) {
  console.error('[translate] ANTHROPIC_API_KEY is required (set TRANSLATE_DRY_RUN=1 to preview).')
  process.exit(1)
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function listMdx(dir) {
  if (!fs.existsSync(dir)) return []
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.mdx'))
    .map((f) => path.join(dir, f))
}

function sha16(s) {
  return crypto.createHash('sha256').update(s).digest('hex').slice(0, 16)
}

function readSourceHash(filePath) {
  if (!fs.existsSync(filePath)) return null
  const src = fs.readFileSync(filePath, 'utf8')
  const m = src.match(/^---\s*\n([\s\S]*?)\n---/m)
  if (!m) return null
  const fm = m[1]
  const h = fm.match(/^sourceHash:\s*['"]?([a-f0-9]+)['"]?\s*$/m)
  return h ? h[1] : null
}

/** Effective hash of a source file: its embedded sourceHash, else a content
 *  hash — so editorial pages (no frontmatter hash) still skip when unchanged. */
function effectiveSourceHash(filePath, content) {
  return readSourceHash(filePath) || sha16(content)
}

function buildSystemPrompt(kind, srcLang, targetLang) {
  const from = LANG_NAME[srcLang] || srcLang
  const to = LANG_NAME[targetLang] || targetLang
  const rtlNote =
    targetLang === 'ar'
      ? '\n- The output IS Arabic prose; produce naturally right-to-left readable Arabic. The markdown source remains LTR — do not add directional control characters.'
      : ''

  if (kind === 'guide') {
    return `You are a professional translator for a consumer help center. Translate the following MDX documentation file from ${from} to ${to}.

Rules:
- PRESERVE the YAML frontmatter delimiters (---) and key names exactly. Translate ONLY the VALUES of 'title' and 'description'. Leave 'sourceHash', 'generated', 'generator', 'templateVersion' (and any other keys) byte-for-byte identical.
- PRESERVE all markdown structure: headings, lists, tables, block quotes, emphasis.
- PRESERVE import lines exactly (e.g. import { Steps, Callout } from 'nextra/components').
- React components: KEEP component names, prop NAMES, JSX structure and icon identifiers (e.g. icon: "help", icon: 'schedule' — Material Symbols names) exactly as-is. TRANSLATE the user-visible string VALUES of props such as title, subtitle, label, desc, q, a, text, note, name, role, tag, steps entries, returnNote content — these are shown to readers.
- KEEP all link targets (hrefs, markdown link URLs) exactly as-is — do NOT translate or alter URLs. Translate only the link TEXT.
- Mermaid blocks (\`\`\`mermaid): keep the diagram syntax and state identifiers unchanged; TRANSLATE only the human labels after a colon (e.g. "received: Reçue" → "received: <translated>").
- Inside JSX prop strings, prefer double quotes as delimiters; NEVER put a straight ' or " INSIDE a string (they would break the MDX build) — use the typographic ’ for apostrophes and “ ” for quotations.
- Numbers, amounts (10 %, 29 €/mois, 25 €), product names (Grubano, Grubano Pro, Uber Eats, Deliveroo, Just Eat) stay as-is (adapt "€/mois" to the target language's convention, e.g. "€/month").
- Keep the warm, pedagogical tone; address the reader with the polite/formal register of the target language (vous → usted / Lei / formal Arabic; English uses "you").${rtlNote}

Output ONLY the translated file content. No explanations. No surrounding code fences.`
  }

  // kind === 'api' (api reference + changelog)
  return `You are a professional technical translator. Translate the following MDX documentation file from ${from} to ${to}.

Rules:
- PRESERVE the YAML frontmatter delimiters (---) and key names exactly. Translate ONLY the VALUES of the keys 'title' and 'description'. Leave 'sourceHash' (and any other keys) byte-for-byte identical.
- PRESERVE all markdown structure: headings, lists, tables (including pipe characters and dashes), block quotes, and link targets.
- PRESERVE all code blocks (inside triple-backtick fences) EXACTLY — do not translate code.
- PRESERVE all inline code (\`...\`) EXACTLY — these are API identifiers like \`/api/orders\`, \`GET\`, \`sessionId\`, status codes like \`200\`. Never translate them.
- PRESERVE all HTML, JSX, and MDX expressions exactly: {/* comments */}, <Component>, etc.
- Translate prose and translatable table-cell values (e.g. "Bad request" → equivalent in target language). Do NOT translate HTTP method names, status codes, endpoint paths, or technical identifiers.
- Translate the auto-generated banner comment {/* AUTO-GENERATED ... */} contents minimally — keep the script reference intact.${rtlNote}

Output ONLY the translated file content. No explanations. No surrounding code fences.`
}

async function callClaude(systemPrompt, userContent) {
  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'x-api-key': API_KEY,
      'anthropic-version': '2023-06-01',
      'content-type': 'application/json',
    },
    body: JSON.stringify({
      model: MODEL,
      max_tokens: 8192,
      system: systemPrompt,
      messages: [{ role: 'user', content: userContent }],
    }),
  })
  if (!res.ok) {
    const text = await res.text().catch(() => '')
    throw new Error(`Claude API ${res.status}: ${text.slice(0, 400)}`)
  }
  const data = await res.json()
  const block = (data.content || []).find((b) => b.type === 'text')
  if (!block || !block.text) throw new Error('Claude API returned no text block')
  return block.text
}

/**
 * Post-process a translated guide:
 *  - strip an accidental whole-file code fence,
 *  - re-point internal /<srcLang>/ links to the target locale,
 *  - normalise elision apostrophes between letters to ’ (MDX-prop safe),
 *  - ensure a sourceHash is present in the frontmatter (inject for editorial
 *    sources that had none, so re-runs can skip).
 */
function postProcess(out, { srcLang, lang, kind, srcHash }) {
  let text = out.trim()
  // Whole-output fence wrap (defensive — same failure mode as the generator).
  const fm = text.match(/^```[a-z]*\s*\n([\s\S]*)\n```\s*$/)
  if (fm && (fm[1].match(/```/g) || []).length % 2 === 0 && /^---/.test(fm[1])) {
    text = fm[1].trim()
  }
  if (kind === 'guide') {
    // Locale swap on internal links (markdown + JSX href props).
    text = text.split(`](/${srcLang}/`).join(`](/${lang}/`)
    text = text.split(`"/${srcLang}/`).join(`"/${lang}/`)
    text = text.split(`'/${srcLang}/`).join(`'/${lang}/`)
    // Elision apostrophes: letter'letter → letter’letter (never a delimiter).
    if (lang !== 'ar') {
      text = text.replace(/([A-Za-zÀ-ÖØ-öø-ÿ])'([A-Za-zÀ-ÖØ-öø-ÿ])/g, '$1’$2')
    }
    // Straight quotes NESTED inside a quoted JSX prop string terminate it
    // early (acorn error → build failure). On `key: "…"` / `key: '…'` prop
    // lines, curl any inner quotes: "x" → “x”, stray " → ”, inner ' → ’.
    text = text.replace(/^(\s*\w+:\s*")(.*)("\s*,?\s*)$/gm, (m, open, inner, close) => {
      if (!inner.includes('"')) return m
      return open + inner.replace(/"([^"]*)"/g, '“$1”').replace(/"/g, '”') + close
    })
    text = text.replace(/^(\s*\w+:\s*')(.*)('\s*,?\s*)$/gm, (m, open, inner, close) => {
      if (!inner.includes("'")) return m
      return open + inner.replace(/'/g, '’') + close
    })
  }
  // The model sometimes invents placeholder frontmatter lines for keys the
  // source never had (editorial pages): `(unchanged)`, `KEEP_ORIGINAL_VALUE`,
  // `[PRESERVED]`, empty… Shape-check the metadata keys and drop any line
  // whose value is not legitimate (placeholders collide with our injection →
  // duplicate-YAML-key build failures).
  const FM_SHAPE = {
    sourceHash: /^['"]?[a-f0-9]+['"]?$/,
    generated: /^(true|false)$/,
    generator: /scripts\//,
    templateVersion: /^\d+$/,
  }
  text = text.replace(/^---\n[\s\S]*?\n---/, (fmBlock) =>
    fmBlock.replace(/^(sourceHash|generated|generator|templateVersion):[ \t]*(.*)\n/gm, (m, key, val) =>
      FM_SHAPE[key].test(val.trim()) ? m : '',
    ),
  )
  // Guarantee a REAL sourceHash in the output frontmatter.
  const fmMatch = text.match(/^---\s*\n([\s\S]*?)\n---/)
  if (fmMatch && !/^sourceHash:\s*['"]?[a-f0-9]+/m.test(fmMatch[1])) {
    text = text.replace(/^---\s*\n/, `---\nsourceHash: ${srcHash}\n`)
  }
  return (text.endsWith('\n') ? text : text + '\n')
}

/** Run async tasks with a concurrency limit. */
async function runWithConcurrency(items, limit, worker) {
  const results = []
  let cursor = 0
  const runners = Array.from({ length: Math.min(limit, items.length) }, async () => {
    while (cursor < items.length) {
      const i = cursor++
      try {
        results[i] = await worker(items[i], i)
      } catch (err) {
        results[i] = { error: err }
      }
    }
  })
  await Promise.all(runners)
  return results
}

/**
 * Build a _meta.ts for an api/changelog target dir based on the .mdx files
 * actually present. Guides _meta.ts files are hand-authored — never touched.
 */
function buildMeta(targetDir, section, langCode) {
  const files = fs
    .readdirSync(targetDir)
    .filter((f) => f.endsWith('.mdx'))
    .map((f) => f.replace(/\.mdx$/, ''))
  if (!files.length) return null

  const indexLabel = INDEX_LABEL[section]?.[langCode] || INDEX_LABEL[section]?.en || 'Index'
  const hasIndex = files.includes('index')
  const others = files.filter((k) => k !== 'index').sort()

  const lines = []
  lines.push('// AUTO-GENERATED by scripts/translate-content.js — do not edit by hand.')
  lines.push("import type { MetaRecord } from 'nextra'")
  lines.push('')
  lines.push('export default {')
  if (hasIndex) lines.push(`  index: ${JSON.stringify(indexLabel)},`)
  for (const k of others) {
    const title = k.charAt(0).toUpperCase() + k.slice(1)
    lines.push(`  ${JSON.stringify(k)}: ${JSON.stringify(title)},`)
  }
  lines.push('} satisfies MetaRecord')
  return lines.join('\n') + '\n'
}

// ── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const tasks = []

  for (const section of SECTIONS) {
    const sectionKey = section.key || section.name
    if (!SECTION_FILTER.includes(sectionKey)) continue
    const srcDir = path.join(CONTENT_DIR, section.srcLang, section.name)
    const sources = section.files
      ? section.files.map((f) => path.join(srcDir, f)).filter((p) => fs.existsSync(p))
      : listMdx(srcDir)
    if (!sources.length) {
      console.warn(`[translate] no source files for section '${sectionKey}' — skipping`)
      continue
    }
    for (const lang of section.targets) {
      if (!LANG_FILTER.includes(lang)) continue
      const outDir = path.join(CONTENT_DIR, lang, section.name)
      for (const srcFile of sources) {
        const fileName = path.basename(srcFile)
        const outFile = path.join(outDir, fileName)
        tasks.push({
          section: section.name,
          sectionKey,
          kind: section.kind,
          srcLang: section.srcLang,
          lang,
          srcFile,
          outFile,
          outDir,
          fileName,
        })
      }
    }
  }

  console.log(
    `[translate] ${tasks.length} candidate file(s). Model=${MODEL} concurrency=${CONCURRENCY} dryRun=${DRY_RUN}`,
  )

  let translated = 0
  let skipped = 0
  let failed = 0

  await runWithConcurrency(tasks, CONCURRENCY, async (t) => {
    const src = fs.readFileSync(t.srcFile, 'utf8')
    const srcHash = effectiveSourceHash(t.srcFile, src)
    const existingHash = readSourceHash(t.outFile)
    if (srcHash && existingHash && srcHash === existingHash) {
      skipped++
      return
    }
    if (DRY_RUN) {
      console.log(`[translate] would translate ${t.lang}/${t.section ? t.section + '/' : ''}${t.fileName} (${t.kind}, from ${t.srcLang})`)
      return
    }
    try {
      const raw = await callClaude(buildSystemPrompt(t.kind, t.srcLang, t.lang), src)
      const out = postProcess(raw, { srcLang: t.srcLang, lang: t.lang, kind: t.kind, srcHash })
      fs.mkdirSync(t.outDir, { recursive: true })
      fs.writeFileSync(t.outFile, out, 'utf8')
      translated++
      console.log(`[translate] wrote ${t.lang}/${t.section ? t.section + '/' : ''}${t.fileName}`)
    } catch (err) {
      failed++
      console.error(`[translate] FAILED ${t.lang}/${t.section ? t.section + '/' : ''}${t.fileName}: ${err.message}`)
    }
  })

  // Auto _meta.ts for api/changelog dirs only (guides _meta is hand-authored).
  for (const section of SECTIONS.filter((s) => s.kind === 'api')) {
    if (!SECTION_FILTER.includes(section.key || section.name)) continue
    for (const lang of section.targets) {
      if (!LANG_FILTER.includes(lang)) continue
      const outDir = path.join(CONTENT_DIR, lang, section.name)
      if (!fs.existsSync(outDir)) continue
      const meta = buildMeta(outDir, section.name, lang)
      if (!meta) continue
      const metaPath = path.join(outDir, '_meta.ts')
      const existing = fs.existsSync(metaPath) ? fs.readFileSync(metaPath, 'utf8') : null
      if (existing !== meta) {
        fs.writeFileSync(metaPath, meta, 'utf8')
        console.log(`[translate] wrote ${path.relative(DOCS_ROOT, metaPath)}`)
      }
    }
  }

  console.log(
    `[translate] done. translated=${translated} skipped(cached)=${skipped} failed=${failed}`,
  )
  if (failed > 0) process.exit(2)
}

main().catch((err) => {
  console.error('[translate] fatal:', err)
  process.exit(1)
})
